### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by avttrue** [alpqr/imgui-qt3d#1]
Hello. I'm learning Qt3D and based on the imgui-qt3d project, I'm trying to write a very, very simple GUI for my test project.
But I encountered difficulties along the way. I don't want to bother you, but the qt3d examples base is very weak. Can I ask you for a consultation? I'll try not to distract you too much. Thanks.

**Comment by Xaekai** [comment]
Seems like the [qtimgui](https://github.com/seanchas116/qtimgui) repo is much more lively* than this one.
